const jobs = new Map<string, {
  id: string;
  status: 'queued' | 'generating' | 'building' | 'completed' | 'error' | 'cancelled';
  progress: number;
  logs: string[];
  appName: string;
  packageName: string;
  requirements: string;
  apiKey: string;
  apiBaseUrl: string;
  downloadUrl: string | null;
  error: string | null;
  createdAt: number;
}>();

export function getJob(jobId: string) {
  return jobs.get(jobId);
}

export function setJob(jobId: string, job: any) {
  jobs.set(jobId, job);
}

export function updateJobProgress(jobId: string, status: string, progress: number, log: string) {
  const job = jobs.get(jobId);
  if (job && job.status !== 'cancelled') {
    job.status = status as any;
    job.progress = progress;
    job.logs.push(log);
  }
}

export function generateId(): string {
  return crypto.randomUUID();
}

export function createMockAPK(): Uint8Array {
  const content = `Mock APK for Cloudflare demo
Generated by APK Generator
This is a placeholder - full Gradle build requires Node.js runtime.

App Information:
- Environment: Cloudflare Pages Functions
- For demo purposes only
`;
  const encoder = new TextEncoder();
  return encoder.encode(content.padEnd(2048, ' '));
}

export async function simulateGeneration(jobId: string, job: any) {
  const steps = [
    { status: 'generating', progress: 5, log: '正在初始化...' },
    { status: 'generating', progress: 15, log: '正在连接 AI 服务...' },
    { status: 'generating', progress: 25, log: '正在分析需求...' },
    { status: 'generating', progress: 40, log: '正在生成项目结构...' },
    { status: 'generating', progress: 50, log: '正在生成 Gradle 配置...' },
    { status: 'generating', progress: 60, log: '正在生成 Android Manifest...' },
    { status: 'generating', progress: 70, log: '正在生成 MainActivity...' },
    { status: 'generating', progress: 80, log: '正在生成布局文件...' },
    { status: 'building', progress: 85, log: '正在编译 APK...' },
    { status: 'building', progress: 95, log: '正在打包 APK...' },
    { status: 'completed', progress: 100, log: 'APK 生成完成！' },
  ];

  for (const step of steps) {
    await new Promise(resolve => setTimeout(resolve, 300));
    const currentJob = jobs.get(jobId);
    if (!currentJob || currentJob.status === 'cancelled') {
      return;
    }
    updateJobProgress(jobId, step.status, step.progress, step.log);
  }

  const finalJob = jobs.get(jobId);
  if (finalJob) {
    finalJob.downloadUrl = `/api/download/${jobId}`;
  }
}
